import { db, companiesTable } from "@workspace/db";

const saudiCompanies = [
  {
    nameEn: "Saudi Aramco",
    nameAr: "أرامكو السعودية",
    industry: "Oil & Gas",
    industryAr: "النفط والغاز",
    city: "Dhahran",
    region: "Eastern Province",
    website: "https://www.aramco.com",
    phone: "+966138730000",
    email: "info@aramco.com",
    description: "Saudi Aramco is the world's largest oil company and a global leader in energy. It manages the world's second-largest proven crude oil reserves and is one of the top five global companies by revenue.",
    descriptionAr: "أرامكو السعودية هي أكبر شركة نفط في العالم وأحد أكبر منتجي البترول والغاز الطبيعي في العالم.",
    employeeCount: 70000,
    revenue: "SAR 1T+",
    foundingYear: 1933,
    crNumber: "2052114575",
    capitalAmount: "SAR 9.4T",
    entityType: "Joint Stock Company",
    companyType: "Public",
    ownerName: "Yasir Al-Rumayyan",
    ownerNameAr: "ياسر الرميان",
    ownerTitle: "Chairman",
    estimatedWealth: "SAR 50B+",
    shareholders: JSON.stringify([{ name: "Kingdom of Saudi Arabia (PIF)", percentage: 90.2 }, { name: "Public Float", percentage: 9.8 }]),
    keyExecutives: JSON.stringify([{ name: "Amin H. Nasser", title: "President & CEO" }, { name: "Khalid Al-Dabbagh", title: "CFO" }]),
    marketPositioning: "World's most valuable oil company and largest producer of crude oil, with unmatched reserve base and low cost of production.",
    recentNews: JSON.stringify([{ headline: "Aramco reports record profits", date: "2024-03", summary: "Saudi Aramco posted record annual profits driven by high oil prices." }]),
    linkedinUrl: "https://linkedin.com/company/aramco",
    twitterUrl: "https://twitter.com/aramco",
    enrichmentScore: 98,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "oil,energy,tasi,mega-cap",
  },
  {
    nameEn: "Saudi Basic Industries Corporation (SABIC)",
    nameAr: "الشركة السعودية للصناعات الأساسية",
    industry: "Petrochemicals",
    industryAr: "البتروكيماويات",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.sabic.com",
    phone: "+966114142000",
    email: "info@sabic.com",
    description: "SABIC is a global diversified chemicals company headquartered in Riyadh, Saudi Arabia. It is one of the world's largest petrochemical companies and a subsidiary of Saudi Aramco.",
    descriptionAr: "سابك شركة كيماويات متنوعة عالمية يقع مقرها الرئيسي في الرياض، المملكة العربية السعودية.",
    employeeCount: 33000,
    revenue: "SAR 160B",
    foundingYear: 1976,
    crNumber: "1010010433",
    capitalAmount: "SAR 53B",
    entityType: "Joint Stock Company",
    companyType: "Public",
    ownerName: "Al-Tayyar Al-Harbi",
    ownerTitle: "CEO",
    estimatedWealth: "SAR 5B+",
    shareholders: JSON.stringify([{ name: "Saudi Aramco", percentage: 70 }, { name: "Public Float", percentage: 30 }]),
    keyExecutives: JSON.stringify([{ name: "Abdulrahman Al-Fageeh", title: "CEO" }, { name: "Fahad Al-Sheaibi", title: "CFO" }]),
    marketPositioning: "One of the world's largest petrochemical companies with operations in over 50 countries.",
    linkedinUrl: "https://linkedin.com/company/sabic",
    enrichmentScore: 95,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "petrochemicals,manufacturing,tasi",
  },
  {
    nameEn: "Saudi Telecom Company (STC)",
    nameAr: "شركة الاتصالات السعودية",
    industry: "Telecommunications",
    industryAr: "الاتصالات",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.stc.com.sa",
    phone: "+96614429999",
    email: "corporate@stc.com.sa",
    description: "STC is the leading telecommunications company in Saudi Arabia and one of the largest telecom groups in the Middle East, offering mobile, fixed-line, internet, and digital services.",
    descriptionAr: "شركة الاتصالات السعودية هي الشركة الرائدة في مجال الاتصالات في المملكة العربية السعودية.",
    employeeCount: 20000,
    revenue: "SAR 64B",
    foundingYear: 1998,
    crNumber: "1010065193",
    capitalAmount: "SAR 20B",
    entityType: "Joint Stock Company",
    companyType: "Public",
    ownerName: "Mohammed Al-Abbar",
    ownerTitle: "Chairman",
    shareholders: JSON.stringify([{ name: "PIF", percentage: 64.5 }, { name: "Public Float", percentage: 35.5 }]),
    keyExecutives: JSON.stringify([{ name: "Olayan Alwetaid", title: "CEO" }]),
    marketPositioning: "Market leader in Saudi telecom with over 25 million subscribers and expanding digital services division.",
    linkedinUrl: "https://linkedin.com/company/stc",
    enrichmentScore: 92,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "telecom,technology,tasi",
  },
  {
    nameEn: "Almarai Company",
    nameAr: "شركة المراعي",
    industry: "Food & Beverage",
    industryAr: "الأغذية والمشروبات",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.almarai.com",
    phone: "+966114702020",
    email: "info@almarai.com",
    description: "Almarai is the world's largest vertically integrated dairy company and the leading food and beverage manufacturing and distribution company in the Middle East.",
    descriptionAr: "المراعي أكبر شركة ألبان متكاملة رأسياً في العالم والشركة الرائدة في تصنيع وتوزيع المواد الغذائية في الشرق الأوسط.",
    employeeCount: 40000,
    revenue: "SAR 18B",
    foundingYear: 1977,
    crNumber: "1010084223",
    capitalAmount: "SAR 10B",
    entityType: "Joint Stock Company",
    companyType: "Public",
    ownerName: "Sultan bin Mohammed Al Kabeer",
    ownerNameAr: "سلطان بن محمد الكبير",
    ownerTitle: "Chairman",
    estimatedWealth: "SAR 10B+",
    shareholders: JSON.stringify([{ name: "Savola Group", percentage: 34.5 }, { name: "Abdullah Al-Issa", percentage: 7.2 }, { name: "Public Float", percentage: 58.3 }]),
    keyExecutives: JSON.stringify([{ name: "Turki Al-Sheikh", title: "CEO" }]),
    marketPositioning: "GCC's largest dairy producer with products distributed across 120+ countries.",
    enrichmentScore: 90,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "food,dairy,tasi,fmcg",
  },
  {
    nameEn: "Al Rajhi Bank",
    nameAr: "مصرف الراجحي",
    industry: "Islamic Banking",
    industryAr: "المصرفية الإسلامية",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.alrajhibank.com.sa",
    phone: "+9664002007777",
    email: "customercare@alrajhibank.com.sa",
    description: "Al Rajhi Bank is one of the largest Islamic banks in the world by assets and one of the largest banks in Saudi Arabia, offering full retail, corporate, and investment banking services.",
    descriptionAr: "مصرف الراجحي أحد أكبر البنوك الإسلامية في العالم من حيث الأصول.",
    employeeCount: 15000,
    revenue: "SAR 25B",
    foundingYear: 1957,
    crNumber: "1010005477",
    capitalAmount: "SAR 40B",
    entityType: "Joint Stock Company",
    companyType: "Public",
    ownerName: "Abdullah Sulaiman Al Rajhi",
    ownerNameAr: "عبدالله سليمان الراجحي",
    ownerTitle: "Chairman",
    estimatedWealth: "SAR 80B+",
    shareholders: JSON.stringify([{ name: "Al Rajhi Family", percentage: 43.2 }, { name: "Public Float", percentage: 56.8 }]),
    keyExecutives: JSON.stringify([{ name: "Waleed Abdullah Al-Mogbel", title: "CEO" }]),
    marketPositioning: "World's largest Islamic bank by market cap, serving over 11 million customers across Saudi Arabia and internationally.",
    enrichmentScore: 93,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "banking,islamic-finance,tasi,financial-services",
  },
  {
    nameEn: "Emaar The Economic City",
    nameAr: "إعمار المدينة الاقتصادية",
    industry: "Real Estate",
    industryAr: "العقارات",
    city: "King Abdullah Economic City",
    region: "Mecca Region",
    website: "https://www.emaaraec.com",
    phone: "+966126003000",
    description: "Emaar Economic City is the master developer of King Abdullah Economic City (KAEC), a mega mixed-use development on the Red Sea coast targeting to be a major industrial and commercial hub.",
    descriptionAr: "إعمار المدينة الاقتصادية هي المطور الرئيسي لمدينة الملك عبدالله الاقتصادية.",
    employeeCount: 1800,
    revenue: "SAR 1.5B",
    foundingYear: 2006,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 78,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "real-estate,construction,tasi",
  },
  {
    nameEn: "Saudi Arabian Mining Company (Ma'aden)",
    nameAr: "معادن",
    industry: "Mining",
    industryAr: "التعدين",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.maaden.com.sa",
    phone: "+966112088888",
    email: "info@maaden.com.sa",
    description: "Ma'aden is the largest mining company in the Middle East and one of the fastest growing mining companies in the world, producing gold, phosphate, aluminium, copper, and other minerals.",
    descriptionAr: "معادن هي أكبر شركة تعدين في الشرق الأوسط وواحدة من أسرع شركات التعدين نمواً في العالم.",
    employeeCount: 8000,
    revenue: "SAR 19B",
    foundingYear: 1997,
    crNumber: "1010165286",
    capitalAmount: "SAR 23.7B",
    entityType: "Joint Stock Company",
    companyType: "Public",
    shareholders: JSON.stringify([{ name: "PIF", percentage: 65.4 }, { name: "Public Float", percentage: 34.6 }]),
    keyExecutives: JSON.stringify([{ name: "Robert Wilt", title: "CEO" }]),
    enrichmentScore: 88,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "mining,metals,tasi",
  },
  {
    nameEn: "Savola Group",
    nameAr: "مجموعة صافولا",
    industry: "Food & Consumer Products",
    industryAr: "المواد الغذائية والسلع الاستهلاكية",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.savola.com",
    phone: "+966126574000",
    description: "The Savola Group is one of Saudi Arabia's largest food companies, with major businesses in edible oils, sugar refining, and retail.",
    descriptionAr: "مجموعة صافولا إحدى أكبر شركات الأغذية في المملكة العربية السعودية.",
    employeeCount: 25000,
    revenue: "SAR 17B",
    foundingYear: 1979,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 82,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "food,retail,tasi",
  },
  {
    nameEn: "Saudi Electricity Company",
    nameAr: "شركة الكهرباء السعودية",
    industry: "Utilities",
    industryAr: "الخدمات العامة",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.se.com.sa",
    phone: "+966114033000",
    description: "Saudi Electricity Company (SEC) is the main power utility in Saudi Arabia, generating, transmitting, and distributing electrical power across the entire Kingdom.",
    descriptionAr: "شركة الكهرباء السعودية هي شركة المرافق الرئيسية في المملكة العربية السعودية.",
    employeeCount: 30000,
    revenue: "SAR 55B",
    foundingYear: 2000,
    companyType: "Public",
    entityType: "Joint Stock Company",
    capitalAmount: "SAR 116B",
    shareholders: JSON.stringify([{ name: "Saudi Aramco", percentage: 6.9 }, { name: "PIF", percentage: 74.3 }, { name: "Public Float", percentage: 18.8 }]),
    enrichmentScore: 85,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "utilities,energy,tasi",
  },
  {
    nameEn: "Jarir Marketing Company",
    nameAr: "مكتبة جرير",
    industry: "Retail",
    industryAr: "التجزئة",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.jarir.com",
    phone: "+966114765555",
    email: "customer@jarir.com",
    description: "Jarir is Saudi Arabia's largest bookstore and electronics retail chain, operating across the GCC with over 65 stores.",
    descriptionAr: "جرير هي أكبر سلسلة متاجر للكتب والإلكترونيات في المملكة العربية السعودية.",
    employeeCount: 7000,
    revenue: "SAR 8B",
    foundingYear: 1974,
    companyType: "Public",
    entityType: "Joint Stock Company",
    ownerName: "Mohammed Abdulaziz Al-Agil",
    ownerTitle: "Chairman",
    estimatedWealth: "SAR 5B+",
    enrichmentScore: 84,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "retail,books,electronics,tasi",
  },
  {
    nameEn: "National Commercial Bank (NCB)",
    nameAr: "البنك الأهلي التجاري",
    industry: "Banking",
    industryAr: "الخدمات المصرفية",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.alahli.com",
    phone: "+966026464646",
    description: "NCB, now merged to form SNB (Saudi National Bank), was Saudi Arabia's largest bank by assets, providing retail, corporate, and investment banking services.",
    descriptionAr: "البنك الأهلي التجاري أكبر بنوك المملكة العربية السعودية من حيث الأصول.",
    employeeCount: 15000,
    revenue: "SAR 22B",
    foundingYear: 1953,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 80,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "banking,financial-services,tasi",
  },
  {
    nameEn: "Riyad Bank",
    nameAr: "بنك الرياض",
    industry: "Banking",
    industryAr: "الخدمات المصرفية",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.riyadbank.com",
    phone: "+966114010001",
    description: "Riyad Bank is one of the largest commercial banks in Saudi Arabia, providing comprehensive retail, corporate, and investment banking services.",
    descriptionAr: "بنك الرياض أحد أكبر البنوك التجارية في المملكة العربية السعودية.",
    employeeCount: 6000,
    revenue: "SAR 9B",
    foundingYear: 1957,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 79,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "banking,financial-services,tasi",
  },
  {
    nameEn: "Abdul Latif Jameel Company",
    nameAr: "شركة عبداللطيف جميل",
    industry: "Automotive & Diversified",
    industryAr: "السيارات والتنويع",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.alj.com",
    phone: "+966126630000",
    description: "Abdul Latif Jameel is one of the largest diversified family business groups in Saudi Arabia, operating in automotive distribution, real estate, energy, and FinTech.",
    descriptionAr: "شركة عبداللطيف جميل من أكبر مجموعات الأعمال العائلية المتنوعة في المملكة العربية السعودية.",
    employeeCount: 15000,
    revenue: "SAR 12B",
    foundingYear: 1945,
    companyType: "Private",
    entityType: "Limited Liability Company",
    ownerName: "Hassan Jameel",
    ownerNameAr: "حسن جميل",
    ownerTitle: "Deputy President",
    estimatedWealth: "SAR 20B+",
    enrichmentScore: 85,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "automotive,private,diversified",
  },
  {
    nameEn: "Saudi Airlines (Saudia)",
    nameAr: "الخطوط الجوية العربية السعودية",
    industry: "Aviation",
    industryAr: "الطيران",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.saudia.com",
    phone: "+966920022222",
    description: "Saudi Airlines (Saudia) is the national carrier of Saudi Arabia, operating a fleet of over 140 aircraft to more than 95 destinations worldwide.",
    descriptionAr: "الخطوط الجوية العربية السعودية هي الناقل الوطني للمملكة العربية السعودية.",
    employeeCount: 35000,
    revenue: "SAR 22B",
    foundingYear: 1945,
    companyType: "Government",
    entityType: "Government Entity",
    enrichmentScore: 82,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "aviation,government,transport",
  },
  {
    nameEn: "Mobily (Etihad Etisalat)",
    nameAr: "موبايلي",
    industry: "Telecommunications",
    industryAr: "الاتصالات",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.mobily.com.sa",
    phone: "+966920002100",
    description: "Mobily is the second largest mobile operator in Saudi Arabia, offering mobile, broadband, and enterprise services to millions of subscribers.",
    descriptionAr: "موبايلي هي ثاني أكبر مشغل للهاتف المحمول في المملكة العربية السعودية.",
    employeeCount: 5000,
    revenue: "SAR 12B",
    foundingYear: 2004,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 80,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "telecom,tasi",
  },
  {
    nameEn: "Dallah Albaraka Group",
    nameAr: "مجموعة دلة البركة",
    industry: "Diversified Financial Services",
    industryAr: "الخدمات المالية المتنوعة",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.dallahgroup.com",
    description: "Dallah Albaraka is a leading Saudi conglomerate with interests in banking, healthcare, media, and real estate, founded by Sheikh Saleh Abdullah Kamel.",
    descriptionAr: "دلة البركة من أكبر المجموعات السعودية المتنوعة التي تعمل في قطاعات البنوك والرعاية الصحية والإعلام والعقارات.",
    employeeCount: 20000,
    revenue: "SAR 10B",
    foundingYear: 1969,
    companyType: "Private",
    entityType: "Holding Company",
    ownerName: "Saleh Abdullah Kamel",
    ownerNameAr: "صالح عبدالله كامل",
    estimatedWealth: "SAR 15B+",
    enrichmentScore: 76,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "conglomerate,private,diversified",
  },
  {
    nameEn: "Saudi Telecom Company Iot (stc pay)",
    nameAr: "إس تي سي باي",
    industry: "FinTech",
    industryAr: "التكنولوجيا المالية",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://stcpay.com.sa",
    description: "stc pay is one of the leading digital wallets and FinTech companies in Saudi Arabia, processing millions of transactions and offering financial services to individuals and businesses.",
    descriptionAr: "stc pay هي من أكبر المحافظ الرقمية وشركات التكنولوجيا المالية في المملكة العربية السعودية.",
    employeeCount: 1000,
    revenue: "SAR 2B",
    foundingYear: 2018,
    companyType: "Private",
    entityType: "Limited Liability Company",
    enrichmentScore: 72,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "fintech,digital,payments",
  },
  {
    nameEn: "Nahdi Medical Company",
    nameAr: "شركة النهدي الطبية",
    industry: "Healthcare & Pharmacy",
    industryAr: "الرعاية الصحية والصيدلة",
    city: "Jeddah",
    region: "Mecca Region",
    website: "https://www.nahdionline.com",
    phone: "+966126652222",
    description: "Nahdi is Saudi Arabia's largest pharmacy chain with over 1,000 branches across the Kingdom, offering pharmacy, healthcare, and wellness products.",
    descriptionAr: "النهدي هي أكبر سلسلة صيدليات في المملكة العربية السعودية بأكثر من 1000 فرع.",
    employeeCount: 12000,
    revenue: "SAR 8B",
    foundingYear: 1986,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 83,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "healthcare,pharmacy,tasi,retail",
  },
  {
    nameEn: "Red Sea International Company",
    nameAr: "شركة البحر الأحمر الدولية",
    industry: "Construction & Infrastructure",
    industryAr: "البناء والبنية التحتية",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.redseainternationa.com",
    description: "Red Sea International is a leading Saudi infrastructure and MEP contracting company specializing in complex industrial and commercial projects across the Gulf region.",
    descriptionAr: "شركة البحر الأحمر الدولية من الشركات الرائدة في مجال البنية التحتية والمقاولات في المملكة.",
    employeeCount: 8000,
    revenue: "SAR 4B",
    foundingYear: 1972,
    companyType: "Public",
    entityType: "Joint Stock Company",
    enrichmentScore: 71,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "construction,infrastructure,tasi",
  },
  {
    nameEn: "Olayan Financing Company",
    nameAr: "مجموعة العليان",
    industry: "Diversified Investment",
    industryAr: "الاستثمار المتنوع",
    city: "Riyadh",
    region: "Riyadh Region",
    website: "https://www.olayan.com",
    description: "Olayan Group is one of Saudi Arabia's most prominent diversified business groups, with significant operations in consumer goods, financial services, real estate, and industrial manufacturing.",
    descriptionAr: "مجموعة العليان من أبرز مجموعات الأعمال السعودية المتنوعة.",
    employeeCount: 50000,
    revenue: "SAR 30B",
    foundingYear: 1947,
    companyType: "Private",
    entityType: "Holding Company",
    ownerName: "Lubna Al-Olayan",
    ownerNameAr: "لبنى العليان",
    ownerTitle: "CEO",
    estimatedWealth: "SAR 40B+",
    enrichmentScore: 88,
    enrichmentStatus: "enriched",
    dataSource: "seed",
    tags: "conglomerate,private,diversified",
  },
];

async function seed() {
  console.log("🌱 Seeding Saudi companies into database...");
  let inserted = 0;
  let skipped = 0;

  for (const company of saudiCompanies) {
    try {
      await db.insert(companiesTable).values(company);
      console.log(`✅ Inserted: ${company.nameEn}`);
      inserted++;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      if (message.includes("duplicate") || message.includes("unique")) {
        console.log(`⏭️  Skipped (already exists): ${company.nameEn}`);
        skipped++;
      } else {
        console.error(`❌ Failed: ${company.nameEn} - ${message}`);
      }
    }
  }

  console.log(`\n✅ Seeding complete! ${inserted} inserted, ${skipped} skipped.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
