export interface DataSourceConfig {
  id: string;
  name: string;
  nameAr: string;
  category: "government" | "directory" | "chamber" | "financial" | "wikidata" | "media" | "exchange" | "jobs" | "enrichment";
  url: string;
  description: string;
  estimatedCompanies: number;
}

export const SAUDI_DATA_SOURCES: DataSourceConfig[] = [
  {
    id: "wikidata",
    name: "Wikidata SPARQL",
    nameAr: "ويكي بيانات",
    category: "wikidata",
    url: "https://query.wikidata.org/sparql",
    description: "726+ Saudi companies with Arabic names, industry, HQ, employees, revenue, websites",
    estimatedCompanies: 726,
  },
  {
    id: "saudi-open-data",
    name: "Saudi Open Data (CKAN)",
    nameAr: "البيانات المفتوحة السعودية",
    category: "government",
    url: "https://data.gov.sa",
    description: "Saudi Open Data API with government-registered company data",
    estimatedCompanies: 2000,
  },
  {
    id: "ministry-commerce",
    name: "Ministry of Commerce",
    nameAr: "وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa",
    description: "Commercial registration and company registry data",
    estimatedCompanies: 5000,
  },
  {
    id: "cma-financial",
    name: "CMA Financial Market Data",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://www.cma.org.sa",
    description: "Listed companies on Tadawul (TASI) and NOMU markets",
    estimatedCompanies: 350,
  },
  {
    id: "tasi-listed",
    name: "Tadawul Listed Companies",
    nameAr: "شركات تداول",
    category: "financial",
    url: "https://www.tadawul.com.sa",
    description: "All companies listed on Saudi Stock Exchange",
    estimatedCompanies: 250,
  },
  {
    id: "yellow-pages-sa",
    name: "Saudi Yellow Pages",
    nameAr: "الصفحات الصفراء السعودية",
    category: "directory",
    url: "https://www.yellowpages.com.sa",
    description: "Business directory with phone, address, categories",
    estimatedCompanies: 8000,
  },
  {
    id: "daleel",
    name: "Daleel Business Directory",
    nameAr: "دليل",
    category: "directory",
    url: "https://www.daleel.sa",
    description: "Comprehensive Saudi business directory",
    estimatedCompanies: 3000,
  },
  {
    id: "kompass-sa",
    name: "Kompass Saudi Arabia",
    nameAr: "كومباس السعودية",
    category: "directory",
    url: "https://sa.kompass.com",
    description: "International B2B directory - Saudi Arabia section",
    estimatedCompanies: 2500,
  },
  {
    id: "franchises-sa",
    name: "Saudi Franchise Directory",
    nameAr: "الامتياز التجاري السعودي",
    category: "directory",
    url: "https://www.saudiFranchise.com",
    description: "Franchise businesses operating in Saudi Arabia",
    estimatedCompanies: 500,
  },
  {
    id: "chamber-riyadh",
    name: "Riyadh Chamber of Commerce",
    nameAr: "غرفة الرياض",
    category: "chamber",
    url: "https://www.riyadhchamber.com",
    description: "Member companies of Riyadh Chamber of Commerce",
    estimatedCompanies: 4000,
  },
  {
    id: "chamber-jeddah",
    name: "Jeddah Chamber of Commerce",
    nameAr: "غرفة جدة",
    category: "chamber",
    url: "https://www.jcci.org.sa",
    description: "Member companies of Jeddah Chamber of Commerce",
    estimatedCompanies: 3500,
  },
  {
    id: "chamber-eastern",
    name: "Eastern Province Chamber",
    nameAr: "غرفة المنطقة الشرقية",
    category: "chamber",
    url: "https://www.chamber.org.sa",
    description: "Dammam/Eastern Province Chamber of Commerce members",
    estimatedCompanies: 2000,
  },
  {
    id: "chamber-madinah",
    name: "Madinah Chamber of Commerce",
    nameAr: "غرفة المدينة المنورة",
    category: "chamber",
    url: "https://www.madina-chamber.org.sa",
    description: "Member companies of Madinah Chamber of Commerce",
    estimatedCompanies: 1200,
  },
  {
    id: "chamber-aseer",
    name: "Aseer Chamber of Commerce",
    nameAr: "غرفة عسير",
    category: "chamber",
    url: "https://www.aseerchamber.org.sa",
    description: "Member companies of Aseer Region Chamber",
    estimatedCompanies: 800,
  },
  {
    id: "bluepages",
    name: "Blue Pages Saudi Arabia",
    nameAr: "الصفحات الزرقاء السعودية",
    category: "directory",
    url: "https://www.bluepages.com.sa",
    description: "Official Saudi business directory covering all companies registered across Saudi chambers of commerce",
    estimatedCompanies: 12000,
  },
  // ── Saudi government open sources (added from builder + masar-harvester) ────
  {
    id: "maroof",
    name: "Maroof — MoC consumer-business registry",
    nameAr: "معروف",
    category: "government",
    url: "https://maroof.sa",
    description: "Ministry of Commerce consumer-business registry with reviews, contact info, categories. Public API at /api/v3.0/Establishments/Search.",
    estimatedCompanies: 35000,
  },
  {
    id: "mc-eservices",
    name: "MoC eServices — Commercial data",
    nameAr: "خدمات وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa/ar/eservices/Pages/Commercial-data.aspx",
    description: "Ministry of Commerce official commercial-data lookup (CR-number based, captcha-gated).",
    estimatedCompanies: 1000000,
  },
  {
    id: "modon",
    name: "MODON — Industrial Cities Authority",
    nameAr: "مدن",
    category: "government",
    url: "https://modon.gov.sa/en/Pages/IndustrialCities.aspx",
    description: "Saudi Industrial Property Authority — tenant companies in industrial cities (manufacturing/heavy industry).",
    estimatedCompanies: 7500,
  },
  {
    id: "monshaat",
    name: "Monsha'at — SME General Authority",
    nameAr: "منشآت",
    category: "government",
    url: "https://www.monshaat.gov.sa",
    description: "Small & Medium Enterprises General Authority — accredited SME directory + KAFALA loan beneficiaries.",
    estimatedCompanies: 18000,
  },
  {
    id: "misa",
    name: "MISA — Ministry of Investment",
    nameAr: "وزارة الاستثمار",
    category: "government",
    url: "https://misa.gov.sa",
    description: "Ministry of Investment licensed foreign-investment companies (was SAGIA).",
    estimatedCompanies: 5000,
  },
  {
    id: "sidf",
    name: "SIDF — Industrial Development Fund",
    nameAr: "صندوق التنمية الصناعية",
    category: "government",
    url: "https://www.sidf.gov.sa",
    description: "Saudi Industrial Development Fund — beneficiary companies, project pipeline.",
    estimatedCompanies: 800,
  },
  {
    id: "zatca",
    name: "ZATCA — Tax & Customs Authority",
    nameAr: "الزكاة والضريبة والجمارك",
    category: "government",
    url: "https://zatca.gov.sa",
    description: "Tax-registered entities (TIN/VAT lookup). Useful for verifying CR ↔ tax registration linkage.",
    estimatedCompanies: 850000,
  },
  {
    id: "sama",
    name: "SAMA — Saudi Central Bank",
    nameAr: "البنك المركزي السعودي",
    category: "financial",
    url: "https://www.sama.gov.sa",
    description: "Licensed banks, insurance companies, finance companies, money exchangers, fintechs.",
    estimatedCompanies: 300,
  },
  {
    id: "mudad",
    name: "Mudad — wage protection",
    nameAr: "مدد",
    category: "government",
    url: "https://mudad.com.sa",
    description: "Mudad employer registry (private-sector employers under Wage Protection System). Headcount + activity signal.",
    estimatedCompanies: 50000,
  },
  {
    id: "wathq",
    name: "Wathq — CR verification",
    nameAr: "وثق",
    category: "government",
    url: "https://wathq.gov.sa",
    description: "Official CR verification + shareholders/board/capital data (gov-grade source for Masar engine).",
    estimatedCompanies: 1200000,
  },
  {
    id: "etimad",
    name: "Etimad — government procurement",
    nameAr: "اعتماد",
    category: "government",
    url: "https://etimad.sa",
    description: "Etimad e-procurement portal — government tenders, awarded contracts, supplier directory (high-intent signal source).",
    estimatedCompanies: 25000,
  },
  {
    id: "momra-licenses",
    name: "MoMRAH — municipal licenses",
    nameAr: "وزارة الشؤون البلدية والقروية والإسكان",
    category: "government",
    url: "https://momra.gov.sa",
    description: "Ministry of Municipal & Rural Affairs and Housing — municipal trade-license registry.",
    estimatedCompanies: 200000,
  },
  {
    id: "stats-sa",
    name: "GASTAT — General Authority for Statistics",
    nameAr: "الهيئة العامة للإحصاء",
    category: "government",
    url: "https://www.stats.gov.sa",
    description: "Open-data datasets, economic-activity classifications, sectoral surveys.",
    estimatedCompanies: 0,
  },
  {
    id: "open-data-portal",
    name: "Saudi Open Data Portal (data.gov.sa)",
    nameAr: "بوابة البيانات المفتوحة",
    category: "government",
    url: "https://data.gov.sa",
    description: "Open Data CKAN API — government datasets, including commercial registers, contracts, sectoral data.",
    estimatedCompanies: 0,
  },
  {
    id: "nitaqat",
    name: "Nitaqat (HRSD) — Saudization tiers",
    nameAr: "نطاقات",
    category: "government",
    url: "https://www.hrsd.gov.sa",
    description: "Ministry of HR Saudization-tier registry (employer compliance level + sector).",
    estimatedCompanies: 200000,
  },
  {
    id: "cma-issuers",
    name: "CMA Issuers Registry",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://cma.org.sa/Market/IssuerInformation",
    description: "Capital Market Authority licensed financial institutions + issuers.",
    estimatedCompanies: 500,
  },
  // ── Saudi compliance + judicial registries (free / no key) ──────────────────
  {
    id: "ncbe",
    name: "NCBE — Saudi Bankruptcy Commission",
    nameAr: "اللجنة الوطنية للإفلاس",
    category: "government",
    url: "https://ncbe.gov.sa",
    description: "National Commercial Bankruptcy Commission — liquidations, restructuring, protective settlements under Bankruptcy Law 2018. Search by CR number.",
    estimatedCompanies: 0,
  },
  {
    id: "najiz",
    name: "Najiz — Ministry of Justice judgments",
    nameAr: "ناجز",
    category: "government",
    url: "https://najiz.sa",
    description: "Public court judgments, litigation history, execution cases, insolvency orders. Search by party name or CR number.",
    estimatedCompanies: 0,
  },
  {
    id: "moci-new-registrations",
    name: "MoCI — Daily new registrations feed",
    nameAr: "وزارة التجارة - السجلات الجديدة",
    category: "government",
    url: "https://mci.gov.sa",
    description: "Ministry of Commerce daily new-CR feed, license renewals, sector stats, foreign-investment approvals. High-value buying-signal source.",
    estimatedCompanies: 50000,
  },
  {
    id: "nic-industrial",
    name: "NIC — National Industrial Cluster Registry",
    nameAr: "السجل الصناعي الوطني",
    category: "government",
    url: "https://nic.org.sa",
    description: "Industrial company registry, factory license data, sector breakdowns, production capacity. Filter by industrial city / sector / product type.",
    estimatedCompanies: 12000,
  },
  {
    id: "hrdf",
    name: "HRDF — Human Resources Development Fund",
    nameAr: "صندوق تنمية الموارد البشرية",
    category: "government",
    url: "https://hrdf.org.sa",
    description: "Registered employers, Saudization ratios, headcount signals (separate dataset from Nitaqat).",
    estimatedCompanies: 60000,
  },
  {
    id: "rcjy",
    name: "RCJY — Jubail & Yanbu Royal Commission",
    nameAr: "الهيئة الملكية للجبيل وينبع",
    category: "government",
    url: "https://rcjy.gov.sa",
    description: "Industrial complex data: project lists, contractor registries, industrial-zone tenants in Jubail + Yanbu. Eastern Province + Western Province industry.",
    estimatedCompanies: 3500,
  },
  {
    id: "scopa",
    name: "SCOPA — Saudi Council of Chambers",
    nameAr: "مجلس الغرف السعودية",
    category: "chamber",
    url: "https://scopa.org.sa",
    description: "Federation of Saudi Chambers of Commerce — member directory across all regional chambers; chamber membership is a wealth/credibility signal.",
    estimatedCompanies: 0,
  },
  {
    id: "wathiq-business",
    name: "Wathiq — KSA CR verification (alt)",
    nameAr: "وثيق",
    category: "government",
    url: "https://wathiq.business.sa",
    description: "Authoritative KSA CR lookup: legal name AR/EN, status, ISIC activity, city/region. Free with registration. Distinct from wathq.gov.sa.",
    estimatedCompanies: 1200000,
  },
  // ── International sanctions (free APIs) ─────────────────────────────────────
  {
    id: "ofac-sdn",
    name: "OFAC SDN List",
    nameAr: "قائمة OFAC",
    category: "government",
    url: "https://sanctionssearch.ofac.treas.gov",
    description: "US Treasury Specially Designated Nationals — 6000+ entries. REST API at ofac.treasury.gov/ofac-api; bulk XML daily.",
    estimatedCompanies: 0,
  },
  {
    id: "un-sanctions",
    name: "UN Security Council Consolidated",
    nameAr: "قائمة الأمم المتحدة",
    category: "government",
    url: "https://scsanctions.un.org",
    description: "Consolidated UN sanctions across Al-Qaida, ISIS, Iran, DPRK, Taliban regimes. XML feed updated daily.",
    estimatedCompanies: 0,
  },
  {
    id: "eu-sanctions",
    name: "EU Consolidated Sanctions",
    nameAr: "قائمة الاتحاد الأوروبي",
    category: "government",
    url: "https://data.europa.eu",
    description: "All EU restrictive measures across sanctions regimes. JSON + XML feeds updated daily.",
    estimatedCompanies: 0,
  },
  // ── Saudi business media (free / freemium) ──────────────────────────────────
  {
    id: "argaam-news",
    name: "Argaam — Saudi financial news",
    nameAr: "أرقام",
    category: "directory",
    url: "https://www.argaam.com",
    description: "Saudi #1 financial news + Tadawul filings in Arabic — corporate actions, earnings, exec changes, M&A. RSS available; freemium tier.",
    estimatedCompanies: 0,
  },
  {
    id: "aleqt",
    name: "Al Eqtisadiah",
    nameAr: "الاقتصادية",
    category: "directory",
    url: "https://www.aleqt.com",
    description: "Saudi economic newspaper — long-form exec profiles, sector analysis, Vision 2030 coverage.",
    estimatedCompanies: 0,
  },
  {
    id: "maal",
    name: "Maal — Saudi financial news",
    nameAr: "مال",
    category: "directory",
    url: "https://maal.com.sa",
    description: "Saudi financial news, restructurings, executive compensation coverage.",
    estimatedCompanies: 0,
  },
  {
    id: "mubasher",
    name: "Mubasher",
    nameAr: "مباشر",
    category: "directory",
    url: "https://mubasher.info",
    description: "Real-time Saudi market intel — same-day deal discovery, board changes, project awards (Arabic-first).",
    estimatedCompanies: 0,
  },
  {
    id: "saudi-gazette-tenders",
    name: "Saudi Gazette — Tender section",
    nameAr: "صحيفة سعودي قازيت",
    category: "government",
    url: "https://saudigazette.com.sa",
    description: "Official government tender gazette — major project awards, giga-project procurements. EN + AR cross-reference.",
    estimatedCompanies: 0,
  },
  // ── Saudi executive directories (free / bypass) ─────────────────────────────
  {
    id: "saudi-ceos",
    name: "SaudiCEOs",
    nameAr: "مدراء عامون سعوديون",
    category: "directory",
    url: "https://saudiceos.com",
    description: "Saudi executive directory by company and sector. Public listings, bypass scrape.",
    estimatedCompanies: 4500,
  },
  {
    id: "saudi-bods",
    name: "SaudiBODs",
    nameAr: "مجالس الإدارة السعودية",
    category: "directory",
    url: "https://saudibods.com",
    description: "Saudi board-of-directors directory by company and sector. Public listings.",
    estimatedCompanies: 3000,
  },
  {
    id: "aamaly",
    name: "Aamaly — Arabic business directory",
    nameAr: "أعمالي",
    category: "directory",
    url: "https://aamaly.com",
    description: "Saudi business directory indexed by Arabic company name. CR verification, AOA extraction (Masar v2 handles).",
    estimatedCompanies: 15000,
  },
  {
    id: "wikipedia-saudi",
    name: "Wikipedia — List of companies of Saudi Arabia",
    nameAr: "قائمة الشركات السعودية - ويكيبيديا",
    category: "wikidata",
    url: "https://en.wikipedia.org/wiki/List_of_companies_of_Saudi_Arabia",
    description: "Wikipedia category + list pages for Saudi companies (Arabic + English). Free, no key.",
    estimatedCompanies: 800,
  },
  // ── GCC neighbouring registries (free, useful for SA-incorporated MNCs) ─────
  {
    id: "ded-dubai",
    name: "DED Dubai — trade license",
    nameAr: "اقتصادية دبي",
    category: "government",
    url: "https://ded.ae",
    description: "Dubai Economic Department trade-license registry. Useful for Saudi companies with Dubai subsidiaries.",
    estimatedCompanies: 350000,
  },
  {
    id: "moec-abudhabi",
    name: "MOEC Abu Dhabi",
    nameAr: "اقتصادية أبوظبي",
    category: "government",
    url: "https://moec.gov.ae",
    description: "Abu Dhabi Department of Economic Development trade-license registry.",
    estimatedCompanies: 200000,
  },
  // ── Open-data enrichment endpoints (Open Data section 3C) ───────────────────
  {
    id: "clearbit-logo",
    name: "Clearbit Logo CDN",
    nameAr: "كليربيت — شعارات الشركات",
    category: "enrichment",
    url: "https://logo.clearbit.com",
    description: "Company logos by domain (PNG/SVG) — no key, no rate limit. Used to enrich the CRM UI.",
    estimatedCompanies: 0,
  },
  {
    id: "github-org",
    name: "GitHub Org",
    nameAr: "GitHub — حسابات الشركات",
    category: "enrichment",
    url: "https://api.github.com",
    description: "Org repositories, hiring signals, open issues, languages. Optional PAT for higher rate limits.",
    estimatedCompanies: 0,
  },
  {
    id: "wappalyzer",
    name: "Wappalyzer — tech-stack fingerprint",
    nameAr: "وابالايزر — بصمة المنصة التقنية",
    category: "enrichment",
    url: "https://www.wappalyzer.com",
    description: "Tech-stack fingerprint, detects GCC payment rails (Tap, PayTabs, HyperPay, Mada). Runs locally; optional API.",
    estimatedCompanies: 0,
  },
  // ── Hiring-signal / job-posting feeds (manual list 3H — free to scrape) ─────
  {
    id: "bayt",
    name: "Bayt — Gulf job postings",
    nameAr: "بيت.كوم",
    category: "jobs",
    url: "https://www.bayt.com/en/saudi-arabia/jobs/",
    description: "Job postings + hiring signals; salary benchmarks across GCC. Already wired in Lead Factory harvester.",
    estimatedCompanies: 0,
  },
  {
    id: "gulftalent",
    name: "GulfTalent — executive search",
    nameAr: "غلف تالنت",
    category: "jobs",
    url: "https://www.gulftalent.com/saudi-arabia/jobs",
    description: "GCC executive search + hiring signals. Free to browse.",
    estimatedCompanies: 0,
  },
  {
    id: "naukrigulf",
    name: "Naukrigulf — job postings",
    nameAr: "نوكري جلف",
    category: "jobs",
    url: "https://www.naukrigulf.com/saudi-arabia-jobs",
    description: "Gulf job listings, company hiring activity signal.",
    estimatedCompanies: 0,
  },
  // ── Saudi business media (section 6) ────────────────────────────────────────
  {
    id: "cnbc-arabia",
    name: "CNBC Arabia",
    nameAr: "سي إن بي سي عربية",
    category: "media",
    url: "https://cnbcarabia.com",
    description: "Real-time Saudi business news, executive interviews, deal announcements, project launches. Free.",
    estimatedCompanies: 0,
  },
  {
    id: "al-arabiya-aswaq",
    name: "Al Arabiya — Aswaq",
    nameAr: "العربية - أسواق",
    category: "media",
    url: "https://www.alarabiya.net/aswaq",
    description: "Al Arabiya financial portal — Saudi market news, exec profiles, M&A, government project news. Bilingual (AR/EN).",
    estimatedCompanies: 0,
  },
  {
    id: "asharq-al-awsat",
    name: "Asharq Al-Awsat",
    nameAr: "الشرق الأوسط",
    category: "media",
    url: "https://aawsat.com",
    description: "Pan-Arab newspaper — Saudi business, GCC deal tracking, government policy, exec appointments. Freemium.",
    estimatedCompanies: 0,
  },
  {
    id: "arab-news",
    name: "Arab News",
    nameAr: "أرب نيوز",
    category: "media",
    url: "https://www.arabnews.com",
    description: "English-language Saudi news — M&A, project awards, exec moves, Vision 2030 contracts. RSS at /rss.xml. Already wired in Lead Factory.",
    estimatedCompanies: 0,
  },
  {
    id: "forbes-middle-east",
    name: "Forbes Middle East",
    nameAr: "فوربس الشرق الأوسط",
    category: "media",
    url: "https://forbesmiddleeast.com",
    description: "Annual Saudi Rich List, top-company lists, CEO profiles, family-wealth stories — HNW wealth signal source.",
    estimatedCompanies: 0,
  },
  {
    id: "wamda-media",
    name: "Wamda — MENA entrepreneurship media",
    nameAr: "ومضة",
    category: "media",
    url: "https://wamda.com",
    description: "Browsing free: MENA deal announcements, exits, founder profiles, ecosystem reports. Best for SME/startup tier deal discovery.",
    estimatedCompanies: 0,
  },
  // ── CMA Announcements (separate from CMA Issuers Registry) ──────────────────
  {
    id: "cma-announcements",
    name: "CMA — corporate announcements",
    nameAr: "هيئة السوق المالية — الإفصاحات",
    category: "government",
    url: "https://cma.org.sa",
    description: "Board decisions, extraordinary GA notices, major acquisitions, compensation policies, exec changes. Cross-references with Tadawul.",
    estimatedCompanies: 0,
  },
  {
    id: "tadawul-disclosures",
    name: "Tadawul — disclosures feed",
    nameAr: "تداول - الإفصاحات",
    category: "exchange",
    url: "https://www.saudiexchange.sa",
    description: "Mandatory CMA disclosures for listed companies: M&A, material contracts, ownership changes, compensation, liquidations.",
    estimatedCompanies: 200,
  },
  {
    id: "yahoo-finance-saudi",
    name: "Yahoo Finance — Saudi tickers (.SR)",
    nameAr: "ياهو فاينانس",
    category: "exchange",
    url: "https://finance.yahoo.com",
    description: "Live prices for Saudi tickers with .SR suffix. Free, no key. Useful for live financial snapshots in profiles.",
    estimatedCompanies: 200,
  },
  // ── GCC stock exchanges (free; section 5) ───────────────────────────────────
  {
    id: "dfm",
    name: "DFM — Dubai Financial Market",
    nameAr: "سوق دبي المالي",
    category: "exchange",
    url: "https://www.dfm.ae",
    description: "Dubai Financial Market listings, financial disclosures.",
    estimatedCompanies: 80,
  },
  {
    id: "adx",
    name: "ADX — Abu Dhabi Securities Exchange",
    nameAr: "سوق أبوظبي للأوراق المالية",
    category: "exchange",
    url: "https://www.adx.ae",
    description: "Abu Dhabi Securities Exchange listings.",
    estimatedCompanies: 100,
  },
  {
    id: "boursa-kuwait",
    name: "Boursa Kuwait",
    nameAr: "بورصة الكويت",
    category: "exchange",
    url: "https://www.boursakuwait.com.kw",
    description: "Kuwait Stock Exchange listings.",
    estimatedCompanies: 200,
  },
  {
    id: "bahrain-bourse",
    name: "Bahrain Bourse",
    nameAr: "بورصة البحرين",
    category: "exchange",
    url: "https://www.bahrainbourse.com",
    description: "Bahrain Exchange listings.",
    estimatedCompanies: 50,
  },
  {
    id: "muscat-msx",
    name: "Muscat Securities Market (MSX)",
    nameAr: "سوق مسقط للأوراق المالية",
    category: "exchange",
    url: "https://www.msx.om",
    description: "Oman Stock Exchange listings.",
    estimatedCompanies: 110,
  },
  // ── GCC neighbouring government registries (free) ───────────────────────────
  {
    id: "difc",
    name: "DIFC — Dubai International Financial Centre",
    nameAr: "مركز دبي المالي العالمي",
    category: "government",
    url: "https://www.difc.ae",
    description: "DIFC-registered companies and funds (Dubai's financial free zone). Useful for Saudi-linked PE/VC entities domiciled in DIFC.",
    estimatedCompanies: 6000,
  },
  {
    id: "adgm",
    name: "ADGM — Abu Dhabi Global Market",
    nameAr: "سوق أبوظبي العالمي",
    category: "government",
    url: "https://www.adgm.com",
    description: "Abu Dhabi Global Market entity registry (financial free zone).",
    estimatedCompanies: 4500,
  },
  {
    id: "qfc-qatar",
    name: "QFC — Qatar Financial Centre",
    nameAr: "مركز قطر للمال",
    category: "government",
    url: "https://www.qfc.qa",
    description: "QFC-registered companies (Qatar financial free zone).",
    estimatedCompanies: 1800,
  },
  {
    id: "cipa-kuwait",
    name: "CIPA — Kuwait Direct Investment Authority",
    nameAr: "هيئة تشجيع الاستثمار المباشر - الكويت",
    category: "government",
    url: "https://www.cipa.gov.kw",
    description: "Kuwait commercial registry (KDIPA — direct investment authority).",
    estimatedCompanies: 0,
  },
  {
    id: "sijilat-bahrain",
    name: "Sijilat — Bahrain commercial registry",
    nameAr: "سجلات - البحرين",
    category: "government",
    url: "https://www.sijilat.com.bh",
    description: "Bahrain Ministry of Industry, Commerce & Tourism — commercial registry.",
    estimatedCompanies: 70000,
  },
  {
    id: "invest-oman",
    name: "Invest in Oman — Ministry of Commerce, Industry & Investment Promotion",
    nameAr: "وزارة التجارة والصناعة وتعزيز الاستثمار - عُمان",
    category: "government",
    url: "https://www.investinoman.com",
    description: "Oman investment authority + company-registry lookups.",
    estimatedCompanies: 0,
  },
  // ── Aamaly variants referenced in masar-harvester ──────────────────────────
  {
    id: "aamaly-emagazine",
    name: "Aamaly — e-magazine (AOA pipeline)",
    nameAr: "مجلة أعمالي الإلكترونية",
    category: "directory",
    url: "https://emagazine.aamaly.sa",
    description: "Aamaly e-magazine search — Articles of Association (AOA) PDFs and corporate filings. Handled by Masar v2 pipeline with Playwright.",
    estimatedCompanies: 8000,
  },
];

// ─── Sector-keyword categories (driven from masar-harvester) ────────────────
// These aren't standalone URL sources — they're the discovery-prompt categories
// that the harvest layer feeds to Perplexity / Gemini / free-search to seed
// company batches per industry. Centralised here so the engines can iterate.

export interface SectorKeyword {
  id: string;
  name: string;
  nameAr: string;
  /** Keywords driven into Tavily / Perplexity / Gemini queries */
  keywords: string[];
}

export const SAUDI_SECTOR_KEYWORDS: SectorKeyword[] = [
  { id: "auditors-accountants", name: "Auditors & Accountants", nameAr: "مكاتب محاسبة ومراجعة",
    keywords: ["audit firm", "chartered accountants", "tax advisory", "SOCPA certified", "external auditor"] },
  { id: "banks-finance", name: "Banks & Finance", nameAr: "البنوك والمالية",
    keywords: ["bank", "Islamic bank", "finance company", "investment bank", "SAMA licensed"] },
  { id: "etimad-suppliers", name: "Etimad Gov. Suppliers", nameAr: "موردو منصة اعتماد",
    keywords: ["government supplier", "Etimad qualified", "Saudi tender winner", "MOH supplier", "MOI contractor"] },
  { id: "healthcare-medical", name: "Healthcare & Medical", nameAr: "الرعاية الصحية والطب",
    keywords: ["hospital", "polyclinic", "medical center", "pharmacy chain", "MOH licensed"] },
  { id: "industrial-manufacturing", name: "Industrial & Manufacturing", nameAr: "الصناعة والتصنيع",
    keywords: ["manufacturer", "factory", "MODON tenant", "industrial production", "OEM"] },
  { id: "law-firms-lawyers", name: "Law Firms & Lawyers", nameAr: "مكاتب المحاماة والقانون",
    keywords: ["law firm", "advocates", "legal consultants", "MoJ licensed", "corporate counsel"] },
  { id: "logistics-freight", name: "Logistics & Freight", nameAr: "اللوجستيات والشحن",
    keywords: ["logistics company", "freight forwarder", "shipping", "customs clearance", "supply chain"] },
  { id: "real-estate-developers", name: "Real Estate Developers", nameAr: "مطورو العقارات",
    keywords: ["real estate developer", "property developer", "REGA licensed", "off-plan sales", "Wafi"] },
  { id: "saudi-contractors", name: "Saudi Contractors", nameAr: "المقاولون السعوديون",
    keywords: ["main contractor", "construction company", "EPC contractor", "Saudi Contractors Authority", "MEED tracked"] },
];
