export interface DataSourceConfig {
  id: string;
  name: string;
  nameAr: string;
  category: "government" | "directory" | "chamber" | "financial" | "wikidata";
  url: string;
  description: string;
  estimatedCompanies: number;
}

export const SAUDI_DATA_SOURCES: DataSourceConfig[] = [
  {
    id: "wikidata",
    name: "Wikidata SPARQL",
    nameAr: "ويكي بيانات",
    category: "wikidata",
    url: "https://query.wikidata.org/sparql",
    description: "726+ Saudi companies with Arabic names, industry, HQ, employees, revenue, websites",
    estimatedCompanies: 726,
  },
  {
    id: "saudi-open-data",
    name: "Saudi Open Data (CKAN)",
    nameAr: "البيانات المفتوحة السعودية",
    category: "government",
    url: "https://data.gov.sa",
    description: "Saudi Open Data API with government-registered company data",
    estimatedCompanies: 2000,
  },
  {
    id: "ministry-commerce",
    name: "Ministry of Commerce",
    nameAr: "وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa",
    description: "Commercial registration and company registry data",
    estimatedCompanies: 5000,
  },
  {
    id: "cma-financial",
    name: "CMA Financial Market Data",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://www.cma.org.sa",
    description: "Listed companies on Tadawul (TASI) and NOMU markets",
    estimatedCompanies: 350,
  },
  {
    id: "tasi-listed",
    name: "Tadawul Listed Companies",
    nameAr: "شركات تداول",
    category: "financial",
    url: "https://www.tadawul.com.sa",
    description: "All companies listed on Saudi Stock Exchange",
    estimatedCompanies: 250,
  },
  {
    id: "yellow-pages-sa",
    name: "Saudi Yellow Pages",
    nameAr: "الصفحات الصفراء السعودية",
    category: "directory",
    url: "https://www.yellowpages.com.sa",
    description: "Business directory with phone, address, categories",
    estimatedCompanies: 8000,
  },
  {
    id: "daleel",
    name: "Daleel Business Directory",
    nameAr: "دليل",
    category: "directory",
    url: "https://www.daleel.sa",
    description: "Comprehensive Saudi business directory",
    estimatedCompanies: 3000,
  },
  {
    id: "kompass-sa",
    name: "Kompass Saudi Arabia",
    nameAr: "كومباس السعودية",
    category: "directory",
    url: "https://sa.kompass.com",
    description: "International B2B directory - Saudi Arabia section",
    estimatedCompanies: 2500,
  },
  {
    id: "franchises-sa",
    name: "Saudi Franchise Directory",
    nameAr: "الامتياز التجاري السعودي",
    category: "directory",
    url: "https://www.saudiFranchise.com",
    description: "Franchise businesses operating in Saudi Arabia",
    estimatedCompanies: 500,
  },
  {
    id: "chamber-riyadh",
    name: "Riyadh Chamber of Commerce",
    nameAr: "غرفة الرياض",
    category: "chamber",
    url: "https://www.riyadhchamber.com",
    description: "Member companies of Riyadh Chamber of Commerce",
    estimatedCompanies: 4000,
  },
  {
    id: "chamber-jeddah",
    name: "Jeddah Chamber of Commerce",
    nameAr: "غرفة جدة",
    category: "chamber",
    url: "https://www.jcci.org.sa",
    description: "Member companies of Jeddah Chamber of Commerce",
    estimatedCompanies: 3500,
  },
  {
    id: "chamber-eastern",
    name: "Eastern Province Chamber",
    nameAr: "غرفة المنطقة الشرقية",
    category: "chamber",
    url: "https://www.chamber.org.sa",
    description: "Dammam/Eastern Province Chamber of Commerce members",
    estimatedCompanies: 2000,
  },
  {
    id: "chamber-madinah",
    name: "Madinah Chamber of Commerce",
    nameAr: "غرفة المدينة المنورة",
    category: "chamber",
    url: "https://www.madina-chamber.org.sa",
    description: "Member companies of Madinah Chamber of Commerce",
    estimatedCompanies: 1200,
  },
  {
    id: "chamber-aseer",
    name: "Aseer Chamber of Commerce",
    nameAr: "غرفة عسير",
    category: "chamber",
    url: "https://www.aseerchamber.org.sa",
    description: "Member companies of Aseer Region Chamber",
    estimatedCompanies: 800,
  },
  {
    id: "bluepages",
    name: "Blue Pages Saudi Arabia",
    nameAr: "الصفحات الزرقاء السعودية",
    category: "directory",
    url: "https://www.bluepages.com.sa",
    description: "Official Saudi business directory covering all companies registered across Saudi chambers of commerce",
    estimatedCompanies: 12000,
  },
  // ── Saudi government open sources (added from builder + masar-harvester) ────
  {
    id: "maroof",
    name: "Maroof — MoC consumer-business registry",
    nameAr: "معروف",
    category: "government",
    url: "https://maroof.sa",
    description: "Ministry of Commerce consumer-business registry with reviews, contact info, categories. Public API at /api/v3.0/Establishments/Search.",
    estimatedCompanies: 35000,
  },
  {
    id: "mc-eservices",
    name: "MoC eServices — Commercial data",
    nameAr: "خدمات وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa/ar/eservices/Pages/Commercial-data.aspx",
    description: "Ministry of Commerce official commercial-data lookup (CR-number based, captcha-gated).",
    estimatedCompanies: 1000000,
  },
  {
    id: "modon",
    name: "MODON — Industrial Cities Authority",
    nameAr: "مدن",
    category: "government",
    url: "https://modon.gov.sa/en/Pages/IndustrialCities.aspx",
    description: "Saudi Industrial Property Authority — tenant companies in industrial cities (manufacturing/heavy industry).",
    estimatedCompanies: 7500,
  },
  {
    id: "monshaat",
    name: "Monsha'at — SME General Authority",
    nameAr: "منشآت",
    category: "government",
    url: "https://www.monshaat.gov.sa",
    description: "Small & Medium Enterprises General Authority — accredited SME directory + KAFALA loan beneficiaries.",
    estimatedCompanies: 18000,
  },
  {
    id: "misa",
    name: "MISA — Ministry of Investment",
    nameAr: "وزارة الاستثمار",
    category: "government",
    url: "https://misa.gov.sa",
    description: "Ministry of Investment licensed foreign-investment companies (was SAGIA).",
    estimatedCompanies: 5000,
  },
  {
    id: "sidf",
    name: "SIDF — Industrial Development Fund",
    nameAr: "صندوق التنمية الصناعية",
    category: "government",
    url: "https://www.sidf.gov.sa",
    description: "Saudi Industrial Development Fund — beneficiary companies, project pipeline.",
    estimatedCompanies: 800,
  },
  {
    id: "zatca",
    name: "ZATCA — Tax & Customs Authority",
    nameAr: "الزكاة والضريبة والجمارك",
    category: "government",
    url: "https://zatca.gov.sa",
    description: "Tax-registered entities (TIN/VAT lookup). Useful for verifying CR ↔ tax registration linkage.",
    estimatedCompanies: 850000,
  },
  {
    id: "sama",
    name: "SAMA — Saudi Central Bank",
    nameAr: "البنك المركزي السعودي",
    category: "financial",
    url: "https://www.sama.gov.sa",
    description: "Licensed banks, insurance companies, finance companies, money exchangers, fintechs.",
    estimatedCompanies: 300,
  },
  {
    id: "mudad",
    name: "Mudad — wage protection",
    nameAr: "مدد",
    category: "government",
    url: "https://mudad.com.sa",
    description: "Mudad employer registry (private-sector employers under Wage Protection System). Headcount + activity signal.",
    estimatedCompanies: 50000,
  },
  {
    id: "wathq",
    name: "Wathq — CR verification",
    nameAr: "وثق",
    category: "government",
    url: "https://wathq.gov.sa",
    description: "Official CR verification + shareholders/board/capital data (gov-grade source for Masar engine).",
    estimatedCompanies: 1200000,
  },
  {
    id: "etimad",
    name: "Etimad — government procurement",
    nameAr: "اعتماد",
    category: "government",
    url: "https://etimad.sa",
    description: "Etimad e-procurement portal — government tenders, awarded contracts, supplier directory (high-intent signal source).",
    estimatedCompanies: 25000,
  },
  {
    id: "momra-licenses",
    name: "MoMRAH — municipal licenses",
    nameAr: "وزارة الشؤون البلدية والقروية والإسكان",
    category: "government",
    url: "https://momra.gov.sa",
    description: "Ministry of Municipal & Rural Affairs and Housing — municipal trade-license registry.",
    estimatedCompanies: 200000,
  },
  {
    id: "stats-sa",
    name: "GASTAT — General Authority for Statistics",
    nameAr: "الهيئة العامة للإحصاء",
    category: "government",
    url: "https://www.stats.gov.sa",
    description: "Open-data datasets, economic-activity classifications, sectoral surveys.",
    estimatedCompanies: 0,
  },
  {
    id: "open-data-portal",
    name: "Saudi Open Data Portal (data.gov.sa)",
    nameAr: "بوابة البيانات المفتوحة",
    category: "government",
    url: "https://data.gov.sa",
    description: "Open Data CKAN API — government datasets, including commercial registers, contracts, sectoral data.",
    estimatedCompanies: 0,
  },
  {
    id: "nitaqat",
    name: "Nitaqat (HRSD) — Saudization tiers",
    nameAr: "نطاقات",
    category: "government",
    url: "https://www.hrsd.gov.sa",
    description: "Ministry of HR Saudization-tier registry (employer compliance level + sector).",
    estimatedCompanies: 200000,
  },
  {
    id: "cma-issuers",
    name: "CMA Issuers Registry",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://cma.org.sa/Market/IssuerInformation",
    description: "Capital Market Authority licensed financial institutions + issuers.",
    estimatedCompanies: 500,
  },
];
