export interface DataSourceConfig {
  id: string;
  name: string;
  nameAr: string;
  category: "government" | "directory" | "chamber" | "financial" | "wikidata";
  url: string;
  description: string;
  estimatedCompanies: number;
}

export const SAUDI_DATA_SOURCES: DataSourceConfig[] = [
  {
    id: "wikidata",
    name: "Wikidata SPARQL",
    nameAr: "ويكي بيانات",
    category: "wikidata",
    url: "https://query.wikidata.org/sparql",
    description: "726+ Saudi companies with Arabic names, industry, HQ, employees, revenue, websites",
    estimatedCompanies: 726,
  },
  {
    id: "saudi-open-data",
    name: "Saudi Open Data (CKAN)",
    nameAr: "البيانات المفتوحة السعودية",
    category: "government",
    url: "https://data.gov.sa",
    description: "Saudi Open Data API with government-registered company data",
    estimatedCompanies: 2000,
  },
  {
    id: "ministry-commerce",
    name: "Ministry of Commerce",
    nameAr: "وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa",
    description: "Commercial registration and company registry data",
    estimatedCompanies: 5000,
  },
  {
    id: "cma-financial",
    name: "CMA Financial Market Data",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://www.cma.org.sa",
    description: "Listed companies on Tadawul (TASI) and NOMU markets",
    estimatedCompanies: 350,
  },
  {
    id: "tasi-listed",
    name: "Tadawul Listed Companies",
    nameAr: "شركات تداول",
    category: "financial",
    url: "https://www.tadawul.com.sa",
    description: "All companies listed on Saudi Stock Exchange",
    estimatedCompanies: 250,
  },
  {
    id: "yellow-pages-sa",
    name: "Saudi Yellow Pages",
    nameAr: "الصفحات الصفراء السعودية",
    category: "directory",
    url: "https://www.yellowpages.com.sa",
    description: "Business directory with phone, address, categories",
    estimatedCompanies: 8000,
  },
  {
    id: "daleel",
    name: "Daleel Business Directory",
    nameAr: "دليل",
    category: "directory",
    url: "https://www.daleel.sa",
    description: "Comprehensive Saudi business directory",
    estimatedCompanies: 3000,
  },
  {
    id: "kompass-sa",
    name: "Kompass Saudi Arabia",
    nameAr: "كومباس السعودية",
    category: "directory",
    url: "https://sa.kompass.com",
    description: "International B2B directory - Saudi Arabia section",
    estimatedCompanies: 2500,
  },
  {
    id: "franchises-sa",
    name: "Saudi Franchise Directory",
    nameAr: "الامتياز التجاري السعودي",
    category: "directory",
    url: "https://www.saudiFranchise.com",
    description: "Franchise businesses operating in Saudi Arabia",
    estimatedCompanies: 500,
  },
  {
    id: "chamber-riyadh",
    name: "Riyadh Chamber of Commerce",
    nameAr: "غرفة الرياض",
    category: "chamber",
    url: "https://www.riyadhchamber.com",
    description: "Member companies of Riyadh Chamber of Commerce",
    estimatedCompanies: 4000,
  },
  {
    id: "chamber-jeddah",
    name: "Jeddah Chamber of Commerce",
    nameAr: "غرفة جدة",
    category: "chamber",
    url: "https://www.jcci.org.sa",
    description: "Member companies of Jeddah Chamber of Commerce",
    estimatedCompanies: 3500,
  },
  {
    id: "chamber-eastern",
    name: "Eastern Province Chamber",
    nameAr: "غرفة المنطقة الشرقية",
    category: "chamber",
    url: "https://www.chamber.org.sa",
    description: "Dammam/Eastern Province Chamber of Commerce members",
    estimatedCompanies: 2000,
  },
  {
    id: "chamber-madinah",
    name: "Madinah Chamber of Commerce",
    nameAr: "غرفة المدينة المنورة",
    category: "chamber",
    url: "https://www.madina-chamber.org.sa",
    description: "Member companies of Madinah Chamber of Commerce",
    estimatedCompanies: 1200,
  },
  {
    id: "chamber-aseer",
    name: "Aseer Chamber of Commerce",
    nameAr: "غرفة عسير",
    category: "chamber",
    url: "https://www.aseerchamber.org.sa",
    description: "Member companies of Aseer Region Chamber",
    estimatedCompanies: 800,
  },
  {
    id: "bluepages",
    name: "Blue Pages Saudi Arabia",
    nameAr: "الصفحات الزرقاء السعودية",
    category: "directory",
    url: "https://www.bluepages.com.sa",
    description: "Official Saudi business directory covering all companies registered across Saudi chambers of commerce",
    estimatedCompanies: 12000,
  },
  // ── Saudi government open sources (added from builder + masar-harvester) ────
  {
    id: "maroof",
    name: "Maroof — MoC consumer-business registry",
    nameAr: "معروف",
    category: "government",
    url: "https://maroof.sa",
    description: "Ministry of Commerce consumer-business registry with reviews, contact info, categories. Public API at /api/v3.0/Establishments/Search.",
    estimatedCompanies: 35000,
  },
  {
    id: "mc-eservices",
    name: "MoC eServices — Commercial data",
    nameAr: "خدمات وزارة التجارة",
    category: "government",
    url: "https://mc.gov.sa/ar/eservices/Pages/Commercial-data.aspx",
    description: "Ministry of Commerce official commercial-data lookup (CR-number based, captcha-gated).",
    estimatedCompanies: 1000000,
  },
  {
    id: "modon",
    name: "MODON — Industrial Cities Authority",
    nameAr: "مدن",
    category: "government",
    url: "https://modon.gov.sa/en/Pages/IndustrialCities.aspx",
    description: "Saudi Industrial Property Authority — tenant companies in industrial cities (manufacturing/heavy industry).",
    estimatedCompanies: 7500,
  },
  {
    id: "monshaat",
    name: "Monsha'at — SME General Authority",
    nameAr: "منشآت",
    category: "government",
    url: "https://www.monshaat.gov.sa",
    description: "Small & Medium Enterprises General Authority — accredited SME directory + KAFALA loan beneficiaries.",
    estimatedCompanies: 18000,
  },
  {
    id: "misa",
    name: "MISA — Ministry of Investment",
    nameAr: "وزارة الاستثمار",
    category: "government",
    url: "https://misa.gov.sa",
    description: "Ministry of Investment licensed foreign-investment companies (was SAGIA).",
    estimatedCompanies: 5000,
  },
  {
    id: "sidf",
    name: "SIDF — Industrial Development Fund",
    nameAr: "صندوق التنمية الصناعية",
    category: "government",
    url: "https://www.sidf.gov.sa",
    description: "Saudi Industrial Development Fund — beneficiary companies, project pipeline.",
    estimatedCompanies: 800,
  },
  {
    id: "zatca",
    name: "ZATCA — Tax & Customs Authority",
    nameAr: "الزكاة والضريبة والجمارك",
    category: "government",
    url: "https://zatca.gov.sa",
    description: "Tax-registered entities (TIN/VAT lookup). Useful for verifying CR ↔ tax registration linkage.",
    estimatedCompanies: 850000,
  },
  {
    id: "sama",
    name: "SAMA — Saudi Central Bank",
    nameAr: "البنك المركزي السعودي",
    category: "financial",
    url: "https://www.sama.gov.sa",
    description: "Licensed banks, insurance companies, finance companies, money exchangers, fintechs.",
    estimatedCompanies: 300,
  },
  {
    id: "mudad",
    name: "Mudad — wage protection",
    nameAr: "مدد",
    category: "government",
    url: "https://mudad.com.sa",
    description: "Mudad employer registry (private-sector employers under Wage Protection System). Headcount + activity signal.",
    estimatedCompanies: 50000,
  },
  {
    id: "wathq",
    name: "Wathq — CR verification",
    nameAr: "وثق",
    category: "government",
    url: "https://wathq.gov.sa",
    description: "Official CR verification + shareholders/board/capital data (gov-grade source for Masar engine).",
    estimatedCompanies: 1200000,
  },
  {
    id: "etimad",
    name: "Etimad — government procurement",
    nameAr: "اعتماد",
    category: "government",
    url: "https://etimad.sa",
    description: "Etimad e-procurement portal — government tenders, awarded contracts, supplier directory (high-intent signal source).",
    estimatedCompanies: 25000,
  },
  {
    id: "momra-licenses",
    name: "MoMRAH — municipal licenses",
    nameAr: "وزارة الشؤون البلدية والقروية والإسكان",
    category: "government",
    url: "https://momra.gov.sa",
    description: "Ministry of Municipal & Rural Affairs and Housing — municipal trade-license registry.",
    estimatedCompanies: 200000,
  },
  {
    id: "stats-sa",
    name: "GASTAT — General Authority for Statistics",
    nameAr: "الهيئة العامة للإحصاء",
    category: "government",
    url: "https://www.stats.gov.sa",
    description: "Open-data datasets, economic-activity classifications, sectoral surveys.",
    estimatedCompanies: 0,
  },
  {
    id: "open-data-portal",
    name: "Saudi Open Data Portal (data.gov.sa)",
    nameAr: "بوابة البيانات المفتوحة",
    category: "government",
    url: "https://data.gov.sa",
    description: "Open Data CKAN API — government datasets, including commercial registers, contracts, sectoral data.",
    estimatedCompanies: 0,
  },
  {
    id: "nitaqat",
    name: "Nitaqat (HRSD) — Saudization tiers",
    nameAr: "نطاقات",
    category: "government",
    url: "https://www.hrsd.gov.sa",
    description: "Ministry of HR Saudization-tier registry (employer compliance level + sector).",
    estimatedCompanies: 200000,
  },
  {
    id: "cma-issuers",
    name: "CMA Issuers Registry",
    nameAr: "هيئة السوق المالية",
    category: "financial",
    url: "https://cma.org.sa/Market/IssuerInformation",
    description: "Capital Market Authority licensed financial institutions + issuers.",
    estimatedCompanies: 500,
  },
  // ── Saudi compliance + judicial registries (free / no key) ──────────────────
  {
    id: "ncbe",
    name: "NCBE — Saudi Bankruptcy Commission",
    nameAr: "اللجنة الوطنية للإفلاس",
    category: "government",
    url: "https://ncbe.gov.sa",
    description: "National Commercial Bankruptcy Commission — liquidations, restructuring, protective settlements under Bankruptcy Law 2018. Search by CR number.",
    estimatedCompanies: 0,
  },
  {
    id: "najiz",
    name: "Najiz — Ministry of Justice judgments",
    nameAr: "ناجز",
    category: "government",
    url: "https://najiz.sa",
    description: "Public court judgments, litigation history, execution cases, insolvency orders. Search by party name or CR number.",
    estimatedCompanies: 0,
  },
  {
    id: "moci-new-registrations",
    name: "MoCI — Daily new registrations feed",
    nameAr: "وزارة التجارة - السجلات الجديدة",
    category: "government",
    url: "https://mci.gov.sa",
    description: "Ministry of Commerce daily new-CR feed, license renewals, sector stats, foreign-investment approvals. High-value buying-signal source.",
    estimatedCompanies: 50000,
  },
  {
    id: "nic-industrial",
    name: "NIC — National Industrial Cluster Registry",
    nameAr: "السجل الصناعي الوطني",
    category: "government",
    url: "https://nic.org.sa",
    description: "Industrial company registry, factory license data, sector breakdowns, production capacity. Filter by industrial city / sector / product type.",
    estimatedCompanies: 12000,
  },
  {
    id: "hrdf",
    name: "HRDF — Human Resources Development Fund",
    nameAr: "صندوق تنمية الموارد البشرية",
    category: "government",
    url: "https://hrdf.org.sa",
    description: "Registered employers, Saudization ratios, headcount signals (separate dataset from Nitaqat).",
    estimatedCompanies: 60000,
  },
  {
    id: "rcjy",
    name: "RCJY — Jubail & Yanbu Royal Commission",
    nameAr: "الهيئة الملكية للجبيل وينبع",
    category: "government",
    url: "https://rcjy.gov.sa",
    description: "Industrial complex data: project lists, contractor registries, industrial-zone tenants in Jubail + Yanbu. Eastern Province + Western Province industry.",
    estimatedCompanies: 3500,
  },
  {
    id: "scopa",
    name: "SCOPA — Saudi Council of Chambers",
    nameAr: "مجلس الغرف السعودية",
    category: "chamber",
    url: "https://scopa.org.sa",
    description: "Federation of Saudi Chambers of Commerce — member directory across all regional chambers; chamber membership is a wealth/credibility signal.",
    estimatedCompanies: 0,
  },
  {
    id: "wathiq-business",
    name: "Wathiq — KSA CR verification (alt)",
    nameAr: "وثيق",
    category: "government",
    url: "https://wathiq.business.sa",
    description: "Authoritative KSA CR lookup: legal name AR/EN, status, ISIC activity, city/region. Free with registration. Distinct from wathq.gov.sa.",
    estimatedCompanies: 1200000,
  },
  // ── International sanctions (free APIs) ─────────────────────────────────────
  {
    id: "ofac-sdn",
    name: "OFAC SDN List",
    nameAr: "قائمة OFAC",
    category: "government",
    url: "https://sanctionssearch.ofac.treas.gov",
    description: "US Treasury Specially Designated Nationals — 6000+ entries. REST API at ofac.treasury.gov/ofac-api; bulk XML daily.",
    estimatedCompanies: 0,
  },
  {
    id: "un-sanctions",
    name: "UN Security Council Consolidated",
    nameAr: "قائمة الأمم المتحدة",
    category: "government",
    url: "https://scsanctions.un.org",
    description: "Consolidated UN sanctions across Al-Qaida, ISIS, Iran, DPRK, Taliban regimes. XML feed updated daily.",
    estimatedCompanies: 0,
  },
  {
    id: "eu-sanctions",
    name: "EU Consolidated Sanctions",
    nameAr: "قائمة الاتحاد الأوروبي",
    category: "government",
    url: "https://data.europa.eu",
    description: "All EU restrictive measures across sanctions regimes. JSON + XML feeds updated daily.",
    estimatedCompanies: 0,
  },
  // ── Saudi business media (free / freemium) ──────────────────────────────────
  {
    id: "argaam-news",
    name: "Argaam — Saudi financial news",
    nameAr: "أرقام",
    category: "directory",
    url: "https://www.argaam.com",
    description: "Saudi #1 financial news + Tadawul filings in Arabic — corporate actions, earnings, exec changes, M&A. RSS available; freemium tier.",
    estimatedCompanies: 0,
  },
  {
    id: "aleqt",
    name: "Al Eqtisadiah",
    nameAr: "الاقتصادية",
    category: "directory",
    url: "https://www.aleqt.com",
    description: "Saudi economic newspaper — long-form exec profiles, sector analysis, Vision 2030 coverage.",
    estimatedCompanies: 0,
  },
  {
    id: "maal",
    name: "Maal — Saudi financial news",
    nameAr: "مال",
    category: "directory",
    url: "https://maal.com.sa",
    description: "Saudi financial news, restructurings, executive compensation coverage.",
    estimatedCompanies: 0,
  },
  {
    id: "mubasher",
    name: "Mubasher",
    nameAr: "مباشر",
    category: "directory",
    url: "https://mubasher.info",
    description: "Real-time Saudi market intel — same-day deal discovery, board changes, project awards (Arabic-first).",
    estimatedCompanies: 0,
  },
  {
    id: "saudi-gazette-tenders",
    name: "Saudi Gazette — Tender section",
    nameAr: "صحيفة سعودي قازيت",
    category: "government",
    url: "https://saudigazette.com.sa",
    description: "Official government tender gazette — major project awards, giga-project procurements. EN + AR cross-reference.",
    estimatedCompanies: 0,
  },
  // ── Saudi executive directories (free / bypass) ─────────────────────────────
  {
    id: "saudi-ceos",
    name: "SaudiCEOs",
    nameAr: "مدراء عامون سعوديون",
    category: "directory",
    url: "https://saudiceos.com",
    description: "Saudi executive directory by company and sector. Public listings, bypass scrape.",
    estimatedCompanies: 4500,
  },
  {
    id: "saudi-bods",
    name: "SaudiBODs",
    nameAr: "مجالس الإدارة السعودية",
    category: "directory",
    url: "https://saudibods.com",
    description: "Saudi board-of-directors directory by company and sector. Public listings.",
    estimatedCompanies: 3000,
  },
  {
    id: "aamaly",
    name: "Aamaly — Arabic business directory",
    nameAr: "أعمالي",
    category: "directory",
    url: "https://aamaly.com",
    description: "Saudi business directory indexed by Arabic company name. CR verification, AOA extraction (Masar v2 handles).",
    estimatedCompanies: 15000,
  },
  {
    id: "wikipedia-saudi",
    name: "Wikipedia — List of companies of Saudi Arabia",
    nameAr: "قائمة الشركات السعودية - ويكيبيديا",
    category: "wikidata",
    url: "https://en.wikipedia.org/wiki/List_of_companies_of_Saudi_Arabia",
    description: "Wikipedia category + list pages for Saudi companies (Arabic + English). Free, no key.",
    estimatedCompanies: 800,
  },
  // ── GCC neighbouring registries (free, useful for SA-incorporated MNCs) ─────
  {
    id: "ded-dubai",
    name: "DED Dubai — trade license",
    nameAr: "اقتصادية دبي",
    category: "government",
    url: "https://ded.ae",
    description: "Dubai Economic Department trade-license registry. Useful for Saudi companies with Dubai subsidiaries.",
    estimatedCompanies: 350000,
  },
  {
    id: "moec-abudhabi",
    name: "MOEC Abu Dhabi",
    nameAr: "اقتصادية أبوظبي",
    category: "government",
    url: "https://moec.gov.ae",
    description: "Abu Dhabi Department of Economic Development trade-license registry.",
    estimatedCompanies: 200000,
  },
];
