import { pgTable, text, serial, timestamp, integer, boolean, decimal } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const companiesTable = pgTable("companies", {
  id: serial("id").primaryKey(),
  nameAr: text("name_ar"),
  nameEn: text("name_en"),
  industry: text("industry"),
  subIndustry: text("sub_industry"),
  industryAr: text("industry_ar"),
  city: text("city"),
  region: text("region"),
  country: text("country").notNull().default("Saudi Arabia"),
  website: text("website"),
  phone: text("phone"),
  email: text("email"),
  contactEmail: text("contact_email"),
  description: text("description"),
  descriptionAr: text("description_ar"),
  employeeCount: text("employee_count"),
  revenue: text("revenue"),
  profit: text("profit"),
  growthRate: text("growth_rate"),
  marketCap: text("market_cap"),
  foundingYear: integer("founding_year"),
  logoUrl: text("logo_url"),
  ceo: text("ceo"),
  founder: text("founder"),
  address: text("address"),
  aiInsights: text("ai_insights"),
  crNumber: text("cr_number"),
  capitalAmount: text("capital_amount"),
  entityType: text("entity_type"),
  companyType: text("company_type"),
  ownerName: text("owner_name"),
  ownerNameAr: text("owner_name_ar"),
  ownerTitle: text("owner_title"),
  ownerPhone: text("owner_phone"),
  ownerEmail: text("owner_email"),
  ownerLinkedin: text("owner_linkedin"),
  estimatedWealth: text("estimated_wealth"),
  shareholders: text("shareholders"),
  keyExecutives: text("key_executives"),
  marketPositioning: text("market_positioning"),
  recentNews: text("recent_news"),
  linkedinUrl: text("linkedin_url"),
  twitterUrl: text("twitter_url"),
  enrichmentScore: integer("enrichment_score"),
  enrichmentStatus: text("enrichment_status"),
  dataSource: text("data_source"),
  tags: text("tags"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertCompanySchema = createInsertSchema(companiesTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertCompany = z.infer<typeof insertCompanySchema>;
export type Company = typeof companiesTable.$inferSelect;
